version: '3.8'

services:
  message-board-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
      - frontend

  message-board-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - message-board-backend
    networks:
      - frontend

networks:
  backend:
  frontend: