version: '3.8'

services:
  message-board-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - neo4j
    environment:
      JDBC_DATABASE_URL: jdbc:neo4j:bolt://neo4j:7687/?user=neo4j,password=password,scheme=basic
    networks:
      - backend
      - frontend

  message-board-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - message-board-backend
    networks:
      - frontend

  neo4j:
    image: neo4j:3.5.28-community
    ports:
      - 7687:7687 #Bolt
      - 7474:7474 #HTTP
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password
    networks:
      - backend

networks:
  backend:
  frontend: