name: Message Board CI

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: .

jobs:
  backend:
    uses: multipristr/message-board/.github/workflows/gradle.yml@main

  frontend:
    uses: multipristr/message-board/.github/workflows/gatsby.yml@main

  compose:

    runs-on: ubuntu-24.04
    needs: [ backend, frontend ]

    steps:
      - uses: actions/checkout@v4.2.1
      - name: Compose Docker services
        run: docker compose build