name: frontend

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: ./frontend

env:
  NODE_ENV: production

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.0
      - name: Setup node 16
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 16.3.0
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run-script build