name: frontend

on:
  workflow_call:

defaults:
  run:
    working-directory: ./frontend

env:
  NODE_ENV: production

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup node 16
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 16.3.0
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run-script build
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3.7.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: "frontend"
          cache-from: type=gha
          cache-to: type=gha,mode=max