name: frontend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.0
      - name: Setup node 16
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 16.3.0
          cache: 'npm'
      - run: npm ci
      - run: npm test